= Introducción

Los modelos de procesamiento del lenguaje natural funcionan sin necesidad de saber lingüística. Sus arquitecturas no contienen reglas gramaticales explícitas, no consultan paradigmas verbales ni categorías morfológicas; aprenden a producir, traducir y entender texto a partir de procesos estadísticos que, en principio, son ciegos a la estructura de la lengua. Y sin embargo, su desempeño sugiere que algo del orden lingüístico queda registrado en su interior @hewitt-manning-2019-structural @tenney-etal-2019-bert @rogers-etal-2020-primer.

Si ese rastro lingüístico existe, hay un lugar donde menos se le suele buscar: el tokenizador. Ese tokenizador es un algoritmo independiente de la red neuronal: antes de que esta procese una oración, la convierte en una secuencia de unidades llamadas subpalabras. En los modelos de lenguaje más usados del momento, ese algoritmo es la codificación de pares de bytes (_Byte Pair Encoding_, BPE), originalmente concebido como un método de compresión de datos @Gage1994ANA. BPE no consulta gramáticas, no parte de un lexicón ni recibe información alguna sobre la lengua que procesa: su única operación es contar pares de símbolos contiguos en un corpus y fusionar los más frecuentes hasta agotar un presupuesto fijo. Por construcción, vive sobre la forma superficial del texto.

Y sin embargo, esa misma elección de subpalabras moldea lo que el modelo puede aprender: distintos tokenizadores producen modelos con desempeños distintos, y ese desempeño cambia según la lengua que se procesa @domingo2019doestokenizationaffectneural @parra2024morphologicaltypologybpesubword. Si BPE fuera realmente ciego a la estructura lingüística, esas asimetrías serían difíciles de explicar.

#cite(<ximena-bpe-2023>, form: "prose") llevaron esa intuición un paso más allá. Definieron tres medidas estadísticas sobre las subpalabras que BPE produce —productividad, frecuencia acumulada e idiosincrasia— y las usaron para construir una representación vectorial de 47 lenguas. Cuando agruparon ese espacio y lo contrastaron contra WALS, una base de datos tipológica clásica, encontraron que las lenguas que BPE percibe como similares también lo son desde el punto de vista lingüístico. El espacio inducido por un algoritmo de compresión parecía recoger algo del paisaje tipológico de las lenguas que comprimía: un primer indicio concreto de la huella que esta tesis se propone caracterizar.

Ese resultado, sin embargo, deja abierta una pregunta de robustez. La comparación se realizó contra una sola base de datos, bajo una sola configuración de agrupamiento y con una sola semilla aleatoria. Si la coincidencia depende de esas decisiones puntuales, el efecto es más una curiosidad metodológica que un hallazgo sobre BPE. Si, por el contrario, sobrevive al cambio de base, al barrido de hiperparámetros y a la comparación contra una línea base aleatoria, el argumento de que BPE codifica información lingüística gana fuerza considerable.

La pregunta concreta que esta tesis se propone responder es, entonces: ¿el agrupamiento que induce el espacio de BPE coincide con el que induce cada base lingüística por encima de lo que cabría esperar al azar, y se mantiene esa coincidencia al variar la base, la dimensionalidad y la semilla?

Para responderla, se extiende el experimento de #cite(<ximena-bpe-2023>, form: "prose") en tres frentes. Primero, para distinguir si la coincidencia depende específicamente de WALS o aparece también frente a otra base tipológica, se incorpora Grambank, con una cobertura gramatical distinta; y para situar esa coincidencia en una escala interpretable, se mide cuánto concuerdan entre sí las propias bases lingüísticas, incluida lang2vec, que sintetiza varias fuentes tipológicas en un único espacio vectorial. Segundo, para caracterizar la distribución de similitudes en lugar de un solo valor puntual, se barre sobre el número de características usadas y sobre miles de pares de semillas aleatorias. Tercero, para distinguir la señal de BPE del ruido, se construye una línea base de referencia mediante agrupamientos aleatorios y se contrasta contra ella.

#pagebreak()
