= Introducción

// Lo siguiente es la justificación y lo vamos a transformar en una introducción
// Por lo tanto, esto es un TODO
El procesamiento del lenguaje natural (PLN) ha transformado significativamente el área de la inteligencia artificial (IA), entre otras cosas, gracias a la creación de los grandes modelos de lenguaje (Large Language Models, LLMs) que dan pié a las aplicaciones generativas de texto. La capacidad de estas tecnologías para procesar y generar texto gramaticalmente correcto, semánticamente contextualizado, han abierto nuevas líneas de investigación sobre cómo las máquinas representan y procesan el lenguaje humano, desde una perspectiva tanto computacional como lingüística.

En PLN, un modelo del lenguaje es la herramienta que permite calcular probabilidades sobre secuencias o cadenas de texto. Hoy en día, estas estimaciones se hacen por medio de complejas arquitecturas de redes neuronales. Además del tipo de red neuronal, los mecanismos de atención y otras sofisticaciones, un componente que es esencial para dar vida a estas tecnologías del lenguaje es la segmentación a nivel subpalabra (un proceso conocido en el área como tokenización).
La segmentación a nivel subpalabra es el proceso de dividir las cadenas de texto en unidades más fundamentales, estas unidades son convertidas después a representaciones numéricas (vectores) que sirven para entrenar una red neuronal artificial. Un modelo del lenguaje no aprende cuáles son las unidades más apropiadas en qué se debe segmentar una cadena en lenguaje natural, más bien, la segmentación es un proceso que se hace a parte y que tiene mucho impacto en el desempeño del sistema final.

Uno de los sistemas de segmentación a nivel subpalabra más ampliamente utilizados en LLMs, particularmente en los modelos de transformador generativo preentrenado (Generative Pre-trained Transformer, GPT), es el basado en el algoritmo BPE. Este algoritmo consiste en identificar y reemplazar iterativamente los pares de caracteres más frecuentes por un nuevo símbolo, generando así unidades denominadas subpalabras.

Puesto que este tipo de métodos son no supervisados y se basan en principios estadísticos de compresión de cadenas, hay una opinión generalizada de que estas tecnologías no se basan en fundamentos lingüísticos. Sin embargo, estudios recientes, como el realizado por Gutierrez-Vasques et al., (2023), sugieren que BPE podría codificar información lingüística. Para demostrarlo, los autores llevaron a cabo un experimento que consistió en: (1) utilizar BPE para caracterizar las lenguas a partir de las propiedades de sus unidades subpalabra; (2) emplear bases de conocimiento lingüístico para representar las lenguas mediante vectores; y (3) comparar, mediante un algoritmo de agrupamiento, si las lenguas se organizan de forma similar en ambos espacios de representación. Los resultados mostraron que las características obtenidas por BPE son capaces de agrupar lenguas que comparten características lingüísticas similares. Lo que indica que este segmentador, aunque aparentemente superficial, puede capturar rasgos estructurales relevantes de las lenguas

No obstante, en su investigación no se consideró la comparación con bases de datos lingüísticas que concentran una amplia gama de lenguas y características gramaticales  tipológicas, como Grambank. Este recurso, desarrollado por la Sociedad Max Planck, constituye una valiosa fuente de información, cuya integración reforzaría sustancialmente la hipótesis sobre la codificación lingüística del algoritmo BPE. Asimismo, el refinamiento en la caracterización vectorial de lenguas y la implementación de métodos de agrupación más sofisticados permitiría un análisis comparativo de mayor precisión, contribuyendo a una validación más robusta de los resultados obtenidos.

De este modo, se parte de algoritmos de segmentación preexistentes, como BPE, a los que se les incorpora un análisis minucioso de las características de las unidades subpalabra generadas, y se propone una metodología computacional para verificar que dichos patrones corresponden con las nociones descritas en estudios lingüísticos. 

En suma, esta tesis busca avanzar en la comprensión del tipo de conocimiento lingüístico que las tecnologías del lenguaje actuales codifican de forma implícita, un objetivo clave en campos como la lingüística computacional y el PLN.

#pagebreak()